x-variables:
  main-image: &main-image us-west1-docker.pkg.dev/digital-ucdavis-edu/wordpress/ucdlib-intranet:dev
  utils-image: &utils-image us-west1-docker.pkg.dev/digital-ucdavis-edu/wordpress/ucdlib-intranet-utils:dev
  wp-gmail-image: &wp-gmail-image us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/gmail-wp-pipeline:dev
  indexer-image: &indexer-image us-west1-docker.pkg.dev/digital-ucdavis-edu/wordpress/ucdlib-intranet-es-indexer:local-dev

services:
  wordpress:
    image: *main-image
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-ucdlib-intranet}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/auth}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/token}
      OIDC_ENDPOINT_LOGOUT_URL: ${OIDC_ENDPOINT_LOGOUT_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/logout}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-openid profile email roles}
      OIDC_LOGIN_TYPE: ${OIDC_LOGIN_TYPE:-auto}
      OIDC_CREATE_IF_DOES_NOT_EXIST: ${OIDC_CREATE_IF_DOES_NOT_EXIST:-true}
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS:-true}
      OIDC_REDIRECT_USER_BACK: ${OIDC_REDIRECT_USER_BACK:-true}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY:-true}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - uploads-data:/usr/src/wordpress/wp-content/uploads
      - wp-logs-data:/var/log/wordpress

  init:
    image: *utils-image
    env_file:
      - .env
    environment:
      RUN_INIT: "true"
      INIT_DATA_ENV: ${INIT_DATA_ENV:-stage}
      SERVER_URL: ${SERVER_URL:-https://stage.staff.library.ucdavis.edu}
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/ucdlib-intranet}
      GC_PROJECT: ${GC_PROJECT:-digital-ucdavis-edu}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../../secrets/gc-reader-key.json:/etc/service-account.json
    command: ./init/init.sh

  backup:
    image: *utils-image
    env_file:
      - .env
    restart: always
    environment:
      RUN_BACKUP: "true"
      BACKUP_DATA_ENV: ${BACKUP_DATA_ENV:-stage}
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/ucdlib-intranet}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../../secrets/gc-writer-key.json:/etc/service-account.json
    command: "./backup/entrypoint.sh"

  wp-gmail:
    image: *wp-gmail-image
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    environment:
      GMAILWP_CRON_SCHEDULE: '*/10 * * * *'
      GMAILWP_INSTANCE_NAME: 'stage'
      GMAILWP_GC_KEY_FILENAME: '/secrets/gc-reader-key.json'
      GMAILWP_LOGGER_ALERT_ON_ERROR: 'true'
      GMAILWP_WP_URL: 'https://stage.staff.library.ucdavis.edu'
      GMAILWP_CUSTOM_SCRIPT: 'ucdlib-intranet'
    volumes:
      - ../../secrets:/secrets

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.5
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.low=100%
      - cluster.routing.allocation.disk.watermark.high=100%
      - cluster.routing.allocation.disk.watermark.flood_stage=100%
      - cluster.routing.allocation.disk.watermark.flood_stage.max_headroom=0b
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  indexer:
    image: *indexer-image
    ports:
      - ${INDEXER_HOST_PORT:-3001}:3000
    env_file:
      - .env
    environment:
      INDEXER_NAME: ${INDEXER_NAME:-ucdlib-intranet-stage}
    depends_on:
      - elasticsearch
      - wordpress
    volumes:
      - ../../../elastic-search:/service
      - /service/node_modules
      - ../../secrets:/secrets
    command: ["tail", "-f", "/dev/null"]

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
  es-data:
